---
name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clone quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 0
          owner: 'jackyzha0'
          repository: 'quartz'

      - name: clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - name: enter repo
        run: cd quartz

      - name: Install Dependencies
        run: npm ci

      - name: Setup quartz
        run: npx quartz create -s ../computer_vision/ -X copy -l shortest

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
